ALL:ejercicio1 ejercicio2 ejercicio3

.PHONY:clean


ejercicio1: Ejercicio1.c
	gcc Ejercicio1.c -lgraph -lm -o ejercicio1

ejercicio2: Ejercicio2.c
	gcc Ejercicio2.c -lgraph -lm -o ejercicio2 

ejercicio3: Ejercicio3.c
	gcc Ejercicio3.c -lgraph -lm -o ejercicio3 


clean:
	\rm -f *.o ejercicio1 ejercicio2 ejercicio3

